export const FETCH_MEDICINE_OPTIONS_REQUEST = 'FETCH_MEDICINE_OPTIONS_REQUEST';
export const FETCH_MEDICINE_OPTIONS_SUCCESS = 'FETCH_MEDICINE_OPTIONS_SUCCESS';
export const FETCH_MEDICINE_OPTIONS_FAILURE = 'FETCH_MEDICINE_OPTIONS_FAILURE';

export const FETCH_RULE_OPTIONS_REQUEST = 'FETCH_RULE_OPTIONS_REQUEST';
export const FETCH_RULE_OPTIONS_SUCCESS = 'FETCH_RULE_OPTIONS_SUCCESS';
export const FETCH_RULE_OPTIONS_FAILURE = 'FETCH_RULE_OPTIONS_FAILURE';

export const FETCH_DOKTER_OPTIONS_REQUEST = 'FETCH_DOKTER_OPTIONS_REQUEST';
export const FETCH_DOKTER_OPTIONS_SUCCESS = 'FETCH_DOKTER_OPTIONS_SUCCESS';
export const FETCH_DOKTER_OPTIONS_FAILURE = 'FETCH_DOKTER_OPTIONS_FAILURE';

export const SAVE_RESEP_REQUEST = 'SAVE_RESEP_REQUEST';
export const SAVE_RESEP_SUCCESS = 'SAVE_RESEP_SUCCESS';
export const SAVE_RESEP_FAILURE = 'SAVE_RESEP_FAILURE';
